Написал базовую логику скраппера
any-nickname/unv-scrapper-service pull request #2
Opened 2024-04-03 16:27 UTC by any-nickname

Написана базовая логика скраппера:
- Парсинг главного каталога (содержащего ссылки на все имеющиеся каталоги на сайте),
- Асинхронный парсинг конкретного каталога (сбор ссылок на изображения всех товаров, содержащихся в конкретном каталоге),
- Асинхронная загрузка изображений (загрузка изображений по ссылкам, собранным в каталогах),
- Логирование происходящих событий как в консоль, так и в лог-файл,
- Папки с изображениями и логами добавлены в .gitignore.

Todo:
- **(done)** Добавить dockerfile с развёртыванием простой базы данных (скорее всего SQLite),
- **(done)** При запуске очередной сессии скраппинга, создавать запись о сессии в базе данных, сохраняя промежуточную информацию (такую как ссылки на все каталоги, ссылки на изображения в каталогах) в базу данных, привязывая их к конкретной сессии скраппинга,
- **(done)** По окончании сессии скраппинга, помечать сессию в базе данных как завершённую,
- **(done)** Если при запуске скраппера обнаруживаем в БД запись о незавершённой сессии, продолжаем её с того момента, где остановились (будет полезно в случае, если программа вылетает, чтобы не терять результат).

**Реализовал то, что перечислял в Todo**

2024-04-04 15:10 UTC, MakDaffi requested changes
В целом не плохо, но есть пару замечаний

2024-04-04 15:10 UTC, MakDaffi commented on unv_scrapper_service/scrapper.py
> +            break
Тут видится 2 проблемы:
1. Нет обработки в случае, если закончилось количеств попыток  (сейчас этот код просто вылетит с ошибкой после выхода из while).
2. Логика реализации ретраев уже присутствует в некоторых библиотеках (например https://tenacity.readthedocs.io/en/latest/) и там она реализована более корректно, поэтому лучше использовать ее. (Но в целом можешь оставить и такую реализацию подправив 1 пункт, просто совет на будущее).

2024-04-04 15:10 UTC, MakDaffi commented on unv_scrapper_service/scrapper.py
> +    batch_size = 20
Немного некорректно прибивать размер батча на гвоздь. Лучше перенеси значения батча в файл `definition.py`.

2024-04-04 15:10 UTC, MakDaffi commented on unv_scrapper_service/scrapper.py
> +    batch_size = 200
Немного некорректно прибивать размер батча на гвоздь. Лучше перенеси значения батча в файл `definition.py`.

2024-04-04 15:10 UTC, MakDaffi commented on .idea/encodings.xml
Папка `.idea` должна быть в `.gitignore`

2024-04-06 11:10 UTC, any-nickname commented on unv_scrapper_service/main.py
> +    asyncio.run(scrapper.parse())
Понял, а изображения сохранять сервис должен по-прежнему в папку на компьютере или отдавать в качестве ответа?
Предполагаю, что первый вариант, т.к. если мы будем отдавать изображения в качестве ответа на запрос к сервису, то при большом количестве изображений их просто будет неудобно скачивать, и пока что я слабо понимаю, как это можно было бы реализовать (массив изображений в ответе метода)

2024-04-06 15:20 UTC, MakDaffi commented on unv_scrapper_service/main.py
> +    asyncio.run(scrapper.parse())
Сохранять в папку + сохранять в бд путь к ним и рассчитанный хэш, т.к. уже на этом этапе можно отбрасывать повторяющиеся изображения

2024-04-07 19:33 UTC, any-nickname commented on unv_scrapper_service/main.py
> +    asyncio.run(scrapper.parse())
Переформатировал проект в веб-сервис с трёхслойной архитектурой, добавил middleware для обработки исключений и много чего ещё, прошу в коммиты ^_^

2024-04-07 19:37 UTC, any-nickname commented on unv_scrapper_service/scrapper.py
> +            break
Добавил создание исключения в случае, если мы потратили все попытки и в итоге не добились ответа от главного каталога. Пользователю вернётся 504-ая ошибка (gateway timeout) и сессия скраппинга прерывается, потому что, по сути, нашим gateway'ем является главный каталог. Если мы не спарсим из него ссылки на все остальные (конкретные) каталоги, продолжить скраппинг не получится. Так что решил в этом случае падать

2024-04-07 19:38 UTC, any-nickname commented on unv_scrapper_service/scrapper.py
> +    batch_size = 20
Размер батча теперь указывается в .env-файле, а в файле `config.py` считывается из переменных окружения. Наверное, нужно добавить в README пример заполнения .env-файла

2024-04-07 19:50 UTC, any-nickname commented on unv_scrapper_service/scrapper.py
> +    batch_size = 200
Размер батча теперь указывается в .env-файле, а в файле config.py считывается из переменных окружения.

2024-04-07 19:51 UTC, any-nickname commented on .idea/encodings.xml
Добавил папку .idea в .gitignore

2024-04-08 13:18 UTC, MakDaffi requested changes
Есть пару не критических замечаний. Подправь их и можешь мерджить без запроса на следующее ревью.

2024-04-08 13:18 UTC, MakDaffi commented on Dockerfile
> +COPY app/ ./app/
Выглядит немного странно. Почему бы просто не установить зависимости с помощью poetry и скопировать папку .venv? Но ладно. Пусть будет так.

2024-04-08 13:18 UTC, MakDaffi commented on app/repository/repository.py
> +            ORDER BY create_timestamp
Создай файлик queries и вынеси весь sql код в него. Иначе код становиться сложно читаемым.

2024-04-08 13:18 UTC, MakDaffi commented on database/initdb/05_database_up.sql
> +COMMENT ON COLUMN public.image_links.is_loaded          IS 'Флаг, было ли изображение загружено';
Объедини все sql файлы в 1. Для создание базы плодить большое количество sql файлов - плохая практика.

2024-04-14 16:40 UTC, any-nickname commented on Dockerfile
> +COPY ./pyproject.toml ./poetry.lock* /tmp/
fixed

2024-04-14 16:40 UTC, any-nickname commented on app/repository/repository.py
> +            ORDER BY create_timestamp
fixed

2024-04-14 16:41 UTC, any-nickname commented on database/initdb/05_database_up.sql
> +COMMENT ON COLUMN public.image_links.is_loaded          IS 'Флаг, было ли изображение загружено';
fixed

2024-04-14 16:41 UTC, merged